#!/usr/bin/perl

# copy-ssh-keys                             Bri Aug 2020
#
# Copy SSH keys and config between ejp hosts

use Getopt::Long;

# parse options

$check = '';
$copy = '';
$verbose = '';

GetOptions ('verbose' => \$verbose, 'check' => \$check, 'copy' => \$copy);

$script = `basename $0`;
chomp($script);

$SSHDIR = "$ENV{'HOME'}/.ssh";

if (! -e $SSHDIR) {
    if ($verbose) {
        print "$script: $SSHDIR does not exist\n";
    }
    exit;
}

$HOST = `hostname`;
chomp($HOST);
if ($HOST eq "ejp-gateway01.ad.ucl.ac.uk") {
    $TARG = 'ejp-gateway02.ad.ucl.ac.uk';
} elsif ($HOST eq "ejp-gateway02.ad.ucl.ac.uk") {
    $TARG = 'ejp-gateway01.ad.ucl.ac.uk';
} else {
    print "$script: Source hostname not recognised\n";
    exit 1;
}

$STAMP = "$SSHDIR/.timestamp";
$FILES = `find $SSHDIR -type f ! -name .timestamp`;

if (! $FILES) {
    if ($verbose) {
        print "$script: no files in $SSHDIR\n";
    }
    exit;
}

if (! -e $STAMP) {
    if ($check || $verbose) {
        print "$0: timestamp does not exist\n";
    }
    $NEWFILES = `find $SSHDIR -type f`;
} else {
    $NEWFILES = `find $SSHDIR -type f -newer $STAMP`;
}

if ($NEWFILES) {
    if ($check || $verbose) {
        print "$script: $SSHDIR has updated files\n";
    }
    if ($copy) {
        if ($verbose) {
            $r = `rsync -av $SSHDIR $TARG:.ssh && touch $STAMP`;
        } else {
            $r = `rsync -a $SSHDIR $TARG:.ssh && touch $STAMP`;
        }
        print $r;
    }
}

